name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: "3.12", os: ubuntu-latest, session: "ruff-check" }
          - { python-version: "3.12", os: ubuntu-latest, session: "ty" }
          - { python-version: "3.12", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.11", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.10", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.12", os: windows-latest, session: "tests" }
          - { python-version: "3.12", os: ubuntu-latest, session: "xdoctest" }
          - { python-version: "3.12", os: ubuntu-latest, session: "docs-build" }

    env:
      NOXSESSION: ${{ matrix.session }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nox
        run: uv tool install nox

      - name: Run Nox
        run: |
          nox --force-color --python=${{ matrix.python-version }}

      - name: Upload documentation
        if: matrix.session == 'docs-build'
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build
